W4D4/ninety_nine_cats_ii/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: redirect('/cats')

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end


# Prefix Verb   URI Pattern                                Controller#Action
#   cats GET    /cats(.:format)                            cats#index
#        POST   /cats(.:format)                            cats#create
# new_cat GET    /cats/new(.:format)                        cats#new
# edit_cat GET    /cats/:id/edit(.:format)                   cats#edit
#    cat GET    /cats/:id(.:format)                        cats#show
#        PATCH  /cats/:id(.:format)                        cats#update
#        PUT    /cats/:id(.:format)                        cats#update


# approve_cat_rental_request POST   /cat_rental_requests/:id/approve(.:format) cat_rental_requests#approve
# deny_cat_rental_request POST   /cat_rental_requests/:id/deny(.:format)    cat_rental_requests#deny
# cat_rental_requests POST   /cat_rental_requests(.:format)             cat_rental_requests#create
# new_cat_rental_request GET    /cat_rental_requests/new(.:format)         cat_rental_requests#new


#   root GET    /                                          redirect(301, /cats)
#  users POST   /users(.:format)                           users#create
# new_user GET    /users/new(.:format)                       users#new
# new_session GET    /session/new(.:format)                     sessions#new
# session DELETE /session(.:format)                         sessions#destroy
#        POST   /session(.:format)

W4D4/ninety_nine_cats_ii/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <ul>
        <li>Logged in as: <%=current_user.user_name%></li>
        <li>
          <form action="<%=session_url%>" method="post">
            <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Logout">
          </form>
        </li>
      </ul>
  <% end %>
    <%= yield %>
  </body>
</html>